### ISSUE TITLE
Coverage stuck at 50%

### ISSUE THREAD

**Issue by Charlotteis** [Charlotteis/possibly#17]
Take a look at my latest coveralls build, which tells me what my code coverage is: https://coveralls.io/builds/9564946

I'm told Index.js has no coverage, and the following line has been highlighted as the culprit:
https://coveralls.io/builds/9564933/source?filename=src%2Findex.js#L9

```javascript
import React from 'react'
```

I really don't think this should be the case.
How can I cover that line so I can raise my code coverage back to 100%?

Any help appreciated!

🌸

**Comment by keithamus** [comment]
Looks like it is actually because that file is never loaded by your test suite, but it is by the coverage tool. The report is slightly erroneous as it suggests the first line is not covered but it's actually the whole file (maybe a coveralls bug?). 

Solution: either tell the coverage tool to ignore index.js, or write a index.test.js file.

**Comment by Charlotteis** [comment]
Ignored the whole file, thank you Keith!
